services:
  - type: web
    name: library-management
    env: python
    buildCommand: ""
    startCommand: gunicorn librarymanagement.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: librarymanagement.settings
      - key: PYTHON_VERSION
        value: 3.10
      - key: DJANGO_SECRET_KEY
        value: your-secret-key-here
      - key: DJANGO_DEBUG
        value: False
    staticPublishPath: staticfiles