"""
Django settings for librarymanagement project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see:
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see:
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# 🔹 Base Directory of the project
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# 🔹 Paths for Templates and Static Files
TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')
STATIC_DIR = os.path.join(BASE_DIR, 'static')

# ---------------- SECURITY SETTINGS ---------------- #

# 🔹 Secret Key (⚠️ Keep it secret in production)
SECRET_KEY = 'k(6-_4sgig$sbrccr2*0=7s)bklpiywi#_121l)s(f8)dq^^wv'

# 🔹 Debug Mode (⚠️ Set to False in production)
DEBUG = True

# 🔹 Allowed Hosts (⚠️ Empty means only localhost allowed)
ALLOWED_HOSTS = []

# ---------------- APPLICATION SETTINGS ---------------- #

# 🔹 Installed Applications
INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'library',  # Library Management App
]

# 🔹 Middleware Configuration
MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 🔹 Root URL Configuration
ROOT_URLCONF = 'librarymanagement.urls'

# ---------------- TEMPLATE SETTINGS ---------------- #

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [TEMPLATE_DIR],  # Template Directory
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

# ---------------- WSGI CONFIGURATION ---------------- #

WSGI_APPLICATION = 'librarymanagement.wsgi.application'

# ---------------- DATABASE CONFIGURATION ---------------- #

# 🔹 Default Database (SQLite3)
DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.sqlite3',
		'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
	}
}

# ---------------- PASSWORD VALIDATION ---------------- #

AUTH_PASSWORD_VALIDATORS = [
	{'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
	{'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
	{'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
	{'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ---------------- INTERNATIONALIZATION ---------------- #

# 🔹 Language and Timezone
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'

# 🔹 Enable Internationalization and Localization
USE_I18N = True
USE_L10N = True
USE_TZ = True

# ---------------- STATIC FILES ---------------- #

# 🔹 Static URL and Directories
STATIC_URL = '/static/'
STATICFILES_DIRS = [STATIC_DIR]

# ---------------- LOGIN CONFIGURATION ---------------- #

# 🔹 Redirect after successful login
LOGIN_REDIRECT_URL = '/afterlogin'

# ---------------- EMAIL CONFIGURATION ---------------- #

# 🔹 SMTP Configuration for Email Services
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587

# 🔹 Uncomment and fill in your credentials for email functionality
# EMAIL_HOST_USER = 'your_email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your_password'